version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Whistlebird1337
      - POSTGRES_USER=whistlebird
      - POSTGRES_DB=postgres
  api:
    build:
      context: ./
      dockerfile: services/api/Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgresql://whistlebird:Whistlebird1337@postgres:5432/postgres